const JalaliCalendar = require('./dist/jalali')
const HijriCalendar = require('./dist/hijri')
const IDate = require('./dist/idate')

const JalaliDate = IDate(JalaliCalendar)
const HijriDate = IDate(HijriCalendar)
// const baseDate = new Date('29 oct 2019')
// const dt = new MyDate(1440, 6, 23) // 23 rajab(06) 1440, 10 farv(00) 98, 30 march(02) 2019
// const dt2 = new MyDate(1440, 6, 24)
// // dt.setMonth(0)
// console.log(dt.toString())
// console.log(dt.di.toString())
// console.log('------------------')
// console.log(dt2.toString())
// console.log(dt2.di.toString())

// console.log('Test...')
// console.log('=================================================')
// const jal = new HijriCalendar()
// const now = Date.now()
// const fromNow = jal.fromTimestamp(Date.now())
// console.log(now)
// console.log(fromNow)
// console.log(jal.toTimestamp(...fromNow))

const tts = new Date('27 sept 1992').getTime()
const date = new JalaliDate(tts)
console.log(date.toString(), date.toISOString())
date.setDate(date.getDate())
date.setDate(date.getDate())
console.log(date.toString(), date.toISOString())

// console.log('My Birthday: 1371/6/5 === 1992/8/27 === 1413/2/29')
// console.log('=================================================')
// const bDayTS = new Date('27 sept 1992').getTime()
// console.log(new JalaliDate(bDayTS).toString())
// console.log(new HijriDate(bDayTS).toString())
// console.log(new Date(bDayTS).toString())

// console.log('')

// console.log('Today')
// console.log('=================================================')
// const nowTS = Date.now()
// console.log(new JalaliDate(nowTS).toString())
// console.log(new HijriDate(nowTS).toString())
// console.log(new Date(nowTS).toString())
